# Generated by Django 5.1.6 on 2025-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "наличные"), ("transfer", "перевод")],
                default="transfer",
                max_length=255,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
