# Generated by Django 5.1.6 on 2025-05-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Сумма оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
