# Generated by Django 5.1.6 on 2025-05-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateField(blank=True, null=True, verbose_name="Дата последнего входа"),
        ),
    ]
