# Generated by Django 5.1.6 on 2025-02-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="materials/preview_lesson",
                verbose_name="Превью урока",
            ),
        ),
    ]
