# Generated by Django 5.1.6 on 2025-06-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ссылка на урок"),
        ),
    ]
