# Generated by Django 5.1.6 on 2025-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="url",
            field=models.CharField(blank=True, null=True, verbose_name="Ссылка на урок"),
        ),
    ]
