# Generated by Django 5.1.6 on 2025-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
